// Writes supabase/migrations/*_seed_content_blocks.sql from the built-in text,
// so the table starts out identical to what the app ships with.
// Run: npx --yes tsx scripts/gen-content-seed.ts
import { writeFileSync } from 'node:fs';
import { BUNDLED_CONTENT, CONTENT_KEYS, CONTENT_SCHEMA_VERSION } from '../lib/content/bundled';

const rows = CONTENT_KEYS.map((key) => {
  const json = JSON.stringify(BUNDLED_CONTENT[key]);
  if (json.includes('$json$')) throw new Error(`unsafe delimiter in ${key}`);
  return `  ('${key}', $json$${json}$json$::jsonb, ${CONTENT_SCHEMA_VERSION})`;
});

const sql = `-- Generated by scripts/gen-content-seed.ts. Existing rows are left untouched so
-- text edited in the database is never overwritten by re-running this seed.
insert into public.content_blocks (key, value, schema_version) values
${rows.join(',\n')}
on conflict (key) do nothing;
`;
const out = 'supabase/migrations/20260921000001_seed_content_blocks.sql';
writeFileSync(out, sql);
console.log(`wrote ${out} (${sql.length} chars, ${rows.length} rows)`);
