// Writes a migration that OVERWRITES the given content_blocks rows with the built-in text.
// Use when bundled text was rewritten and the server still holds the old copy (the seed
// never overwrites existing rows, and server text wins over the bundled text in the app).
// Run: npx tsx scripts/gen-content-update.ts <YYYYMMDDHHMMSS_name> KEY [KEY...]
import { writeFileSync } from 'node:fs';
import { BUNDLED_CONTENT, CONTENT_KEYS, CONTENT_SCHEMA_VERSION, ContentKey } from '../lib/content/bundled';

const [name, ...keys] = process.argv.slice(2);
if (!name || keys.length === 0) throw new Error('usage: gen-content-update.ts <YYYYMMDDHHMMSS_name> KEY [KEY...]');
for (const key of keys) if (!(CONTENT_KEYS as string[]).includes(key)) throw new Error(`unknown content key: ${key}`);

const rows = (keys as ContentKey[]).map((key) => {
  const json = JSON.stringify(BUNDLED_CONTENT[key]);
  if (json.includes('$json$')) throw new Error(`unsafe delimiter in ${key}`);
  return `  ('${key}', $json$${json}$json$::jsonb, ${CONTENT_SCHEMA_VERSION})`;
});

const sql = `-- Generated by scripts/gen-content-update.ts. Overwrites these rows with the app's built-in text:
-- ${keys.join(', ')}
insert into public.content_blocks (key, value, schema_version) values
${rows.join(',\n')}
on conflict (key) do update set value = excluded.value, schema_version = excluded.schema_version;
`;
const out = `supabase/migrations/${name}.sql`;
writeFileSync(out, sql);
console.log(`wrote ${out} (${rows.length} rows)`);
